### ISSUE TITLE
Dealabs cog crash

### ISSUE THREAD

**Issue by Sergeileduc** [Azrood/DCTbot#102]
Issue in dealabs :

```log
2020-04-17 19:26:38,948 Bot: |                 discord.ext.tasks |    ERROR | Internal background task failed.
Traceback (most recent call last):
  File "/home/ady/.local/lib/python3.6/site-packages/discord/ext/tasks/__init__.py", line 68, in _loop
    await self.coro(*args, **kwargs)
  File "/sftp/dctbot/incoming/dctbot/cogs/dealabs.py", line 41, in auto_free_games
    free_game_list = await get_free_games()
  File "/sftp/dctbot/incoming/dctbot/cogs/dealabs.py", line 26, in get_free_games
    for r in res
  File "/sftp/dctbot/incoming/dctbot/cogs/dealabs.py", line 27, in <listcomp>
    if "jeu" in r[0].text
IndexError: list index out of range
```

**Comment by Azrood** [comment]
fixed
